name: GPU Info Checker

on:
  workflow_dispatch:

jobs:
  check-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Show GPU Information (if available)
        run: |
          echo "🔍 Checking GPU..."
          if command -v nvidia-smi &> /dev/null
          then
            echo "✅ GPU detected! Running nvidia-smi..."
            nvidia-smi
          else
            echo "❌ No NVIDIA GPU found or nvidia-smi not installed."
          fi
