name: CPU Info Checker

on:
  workflow_dispatch:

jobs:
  check-cpu:
    runs-on: ubuntu-latest

    steps:
    - name: Show basic CPU information
      run: |
        echo "🧠 Checking CPU information..."
        echo ""
        echo "▶️ Total Threads (vCPU):"
        nproc
        echo ""
        echo "▶️ Full CPU Info:"
        lscpu
        echo ""
        echo "▶️ /proc/cpuinfo Summary:"
        grep -E 'model name|cpu cores|siblings|MHz' /proc/cpuinfo | sort | uniq
